name: Students Performance Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: 'MLProject/data/final_data_students.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo 'CSV URL is ${{ env.CSV_URL }}'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f MLProject/requirements.txt ]; then
            pip install -r MLProject/requirements.txt
          else
            pip install mlflow scikit-learn pandas numpy matplotlib seaborn
          fi
      
      # Run MLflow Project
      - name: Run mlflow project
        run: |
          cd MLProject
          rm -rf mlruns
          rm -rf run_id.txt
          mlflow run . --env-manager=local

      # Read and Set Run ID
      - name: Get latest Mlflow run_id
        run: |
          cd MLProject
          
          RUN_ID=$(cat run_id.txt)
          echo "Captured MLFLOW_RUN_ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      # 7. Setup Git LFS & Track mlruns
      - name: Set up Git LFS
        run: |
           git config --global user.name ${{ secrets.username }}
           git config --global user.email ${{ secrets.email }}
           git lfs install
           git lfs track "MLProject/mlruns/**"
           git add .gitattributes
           git commit -m "Track large files in mlruns with Git LFS" || true
           git pull origin main --rebase
           git push origin main

      # 8. Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git add -f MLProject/mlruns/
          git add MLProject/run_id.txt
          git commit -m "Save mlruns from CI run (Run ID: ${{ env.RUN_ID }})" || true
          git pull origin main --rebase
          git push origin main


          