name: Students Performance Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: 'data/final_data_students.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo 'CSV URL is ${{ env.CSV_URL }}'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f MLProject/requirements.txt ]; then
            pip install -r MLProject/requirements.txt
      
      # Run MLflow Project
      - name: Run MLflow Project Tuning
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --env-manager local

      # Extract the absolute best Run ID generated by the Python script
      - name: Read Best Run ID
        run: |
          if [ ! -f MLProject/run_id.txt ]; then
            echo "Error: run_id.txt not found!"
            exit 1
          fi
          RUN_ID=$(cat MLProject/run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Successfully retrieved Best Run ID: $RUN_ID"

      # Download the 5 best parameters artifacts + model binary back from DagsHub
      - name: Download Best Artifacts from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/seprianto15/Workflow-CI.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow artifacts download \
            --run-id "$RUN_ID" \
            -d downloaded_artifacts

      # Upload the downloaded artifacts to GitHub Actions storage
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v5
        with:
          name: students-performance-best-model
          path: downloaded_artifacts
