name: Students Performance Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CSV_URL: 'MLProject/data/final_data_students.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo 'CSV URL is ${{ env.CSV_URL }}'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f MLProject/requirements.txt ]; then
            pip install -r MLProject/requirements.txt
          else
            pip install mlflow scikit-learn pandas numpy matplotlib seaborn
          fi
      
      # Run MLflow Project
      - name: Run ml flow project
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/seprianto15/Workflow-CI.mlflow
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --env-manager local

      # Extract the absolute best Run ID generated by the Python script
      - name: Pull Run ID to Main Root
        run: |
          if [ -f MLProject/run_id.txt ]; then
            mv MLProject/run_id.txt ./run_id.txt
            echo "BEST_RUN_ID=$(cat run_id.txt)" >> $GITHUB_ENV
          else
            echo "Error: run_id.txt not found inside MLProject folder."
            ls -la MLProject/
            exit 1
          fi
      # Download the 5 best parameters artifacts + model binary back from DagsHub
      - name: Download Best Artifacts from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/seprianto15/Workflow-CI.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "Downloading artifacts for Run ID: ${{ env.BEST_RUN_ID }}"
          mlflow artifacts download \
            --run-id "${{ env.BEST_RUN_ID }}" \
            -d downloaded_artifacts

      # Upload the downloaded artifacts to GitHub Actions storage
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v5
        with:
          name: students-performance-best-model
          path: downloaded_artifacts

      - name: Workflow Completed
        run: |
          echo 'Training completed successfully'
          echo 'Best artifacts successfully uploaded to GitHub'